---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: create a system group for jira
  group:
    name: '{{ jira_group }}'
    state: present
    system: yes

- name: create a system user for running jira
  user:
    name: '{{ jira_user }}'
    group: '{{ jira_group }}'
    home: '{{ jira_home }}'
    createhome: no
    state: present
    system: yes

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ jira_catalina_install }}", owner: "{{ jira_user }}", group: "{{ jira_group }}", mode: "0755", state: "directory" }
    - { dest: "{{ jira_home }}", owner: "{{ jira_user }}", group: "{{ jira_group }}", mode: "0755", state: "directory" }
  tags: jira

- name: unarchive package
  shell: |
    ARCHIVE="`mktemp --suffix=tar.gz`"
    curl -sL {{ jira_url }} > $ARCHIVE
    tar zxf $ARCHIVE -C {{ jira_catalina_install }} --strip-components=1
    chown -Rf {{ jira_user }}:{{ jira_group }} {{ jira_catalina_install }}
    rm -rf $ARCHIVE
  args:
    creates: "{{ jira_catalina_install }}/bin/start-jira.sh"
  tags: jira

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/jira.j2", dest: "/etc/init.d/jira", owner: "root", group: "root", mode: "0755" }
    - { src: "opt/atlassian/jira/bin/setenv.sh.j2", dest: "{{ jira_catalina_install }}/bin/setenv.sh", owner: "{{ jira_user }}", group: "{{ jira_group }}", mode: "0644" }
    - { src: "opt/atlassian/jira/conf/server.xml.j2", dest: "{{ jira_catalina_install }}/conf/server.xml", owner: "{{ jira_user }}", group: "{{ jira_group }}", mode: "0644" }
  tags: jira

- name: link installed jira version to runtime dir
  file:
    state: link
    force: yes
    src: '{{ jira_catalina_install }}'
    dest: '{{ jira_catalina }}'

- name: enable service
  service:
    name: "jira"
    enabled: "yes"
  tags: jira
